[package]
name = "pure_search_battle_server"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.100"
axum = "0.8.8"
tokio = { version = "1.49.0", features = ["full"] }
serde.workspace = true
serde_json.workspace = true
